### PR TITLE
Payload v2

### PR DESCRIPTION
**Pull request by imalsogreg**
This updates the Wai.Response -> Object encoder and the Object -> Wai.Request encoders for the current payload format, addressing #4 and #5.

### CODE REVIEW

**Comment by nmattia** [comment]
Hey Greg that's awesome! I don't use wai-lambda much anymore, but I'm happy to merge this as is! I had a brief look and lgtm!

**Comment by imalsogreg** [comment]
@nmattia , awesome, thank you!

I hate to ask for a version bump and a cabal release on a package you don't use anymore. Would that be a big inconvenience? Or would you be willing to give me push rights to hackage?

**Comment by imalsogreg** [comment]
Ah, I noticed that I accidentally changed a type:

old: `parseRequest :: Aeson.Value -> Aeson.Parser (IO Wai.Request)`
new: `parseRequest :: Aeson.Object -> Aeson.Parser (IO Wai.Request)`

Happy to change it back if you care.

**Comment by nmattia** [comment]
>  version bump and a cabal release 

No problem! shall I merge this first or do you want to swap `Object` back to `Value`? I think a request can only ever be an `Object` so the new signature works for me

**Comment by imalsogreg** [comment]
`Object` works for me :)

**Comment by nmattia** [comment]
Thanks @imalsogreg ! I'll merge and push the dist asap

EDIT: done :)

**Pull request merged**
